### ISSUE TITLE
sry, I cann`t run it

### ISSUE THREAD

**Issue by qingwu-aby** [fuse-box/react-example#20]
```
/Users/admin/react-example/node_modules/fuse-box/Utils.js:68
function uglify(contents, { es6 = false, ...opts } = {}) {
                                         ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/admin/react-example/node_modules/fuse-box/CacheBreaker.js:5:17)
```

**Comment by nchanged** [comment]
Hi @Yuan-Far 
If you carefully read the documentation you will see that FuseBox requires Node.js > 8.2 to run. Please upgrade your NodeJS and try again.

Cheers.
