### ISSUE TITLE
new fuse.ts doesn't run as per instructions :/

### ISSUE THREAD

**Issue by asfaltboy** [fuse-box/react-example#22]
```bash
$ npm install
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-example@1.0.0 No description
npm WARN react-example@1.0.0 No repository field.

audited 867 packages in 4.079s
found 0 vulnerabilities

node fuse.ts
/Users/pavel.savchenko/github/react-example/fuse.ts:1
import { fusebox, sparky } from "fuse-box";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by nchanged** [comment]
It's a typescript file not JavaScript ) npm start or ts-node -T fuse.ts
